# This configuration provides a Semtech UDP packet-forwarder backend and
# integrates with a MQTT broker. Many options and defaults have been omitted
# for simplicity.
#
# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.

#This gateway ID: e45f01fffe46768e

# Gateway backend configuration.
[backend]
# Backend type.
type="semtech_udp"

  # Semtech UDP packet-forwarder backend.
  [backend.semtech_udp]

  # ip:port to bind the UDP listener to
  #
  # Example: 0.0.0.0:1700 to listen on port 1700 for all network interfaces.
  # This is the listener to which the packet-forwarder forwards its data
  # so make sure the 'serv_port_up' and 'serv_port_down' from your
  # packet-forwarder matches this port.
  udp_bind = "0.0.0.0:1700"


# Integration configuration.
[integration]
# Payload marshaler.
#
# This defines how the MQTT payloads are encoded. Valid options are:
# * protobuf:  Protobuf encoding (required for chirpstack v4)
# * json:      JSON encoding (easier for debugging, but less compact than 'protobuf')
marshaler="protobuf"

  # MQTT integration configuration.
  [integration.mqtt]
  # Event topic template.
  event_topic_template="gateway/{{ .GatewayID }}/event/{{ .EventType }}"

  # update template as per Chirpstack v4 or change the server config to match
  #event_topic_tempelate="eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}"

  #Command topic template.
  command_topic_template="gateway/{{ .GatewayID }}/command/#"

  #update template as per chirpstack v4 from docker compose file configuration or change the server config to match
  #command_topic_tempelate = "eu868/gateway/{{ .GatewayID }}/command/#"

  #This needs to be non zero for connecting to the external databus
  keep_alive="30s"

  #MQTT authentication.
  [integration.mqtt.auth]
  # Type defines the MQTT authentication type to use.
  #
  # Set this to the name of one of the sections below.
  type="generic"

    # Generic MQTT authentication.
    [integration.mqtt.auth.generic]
    # MQTT server (e.g. scheme://host:port where scheme is tcp, ssl or ws)
    # insecure server on edge device
    #server = "<IP Address of edge device>:9883"
    # secure server on edge device
    server = "ssl://<IP Address of edge device>:9883"

    # Connect with the given username (optional)
    username="<username configured in external databus>"

    # Connect with the given password (optional)
    password="<password configured in external databus>"

    #client_id=""

    # CA certificate file (optional)
    #
    # Use this when setting up a secure connection (when server uses ssl://...)
    # but the certificate used by the server is not trusted by any CA certificate
    # on the server (e.g. when self generated).
    ca_cert="<absolute path .e.g: /etc/chirpstack-gateway-bridge/thetaphi-ca.crt>"

    # mqtt TLS certificate file (optional)
    tls_cert="<absolute path .e.g: /etc/chirpstack-gateway-bridge/ievd-v1-12.crt>"
    
    # mqtt TLS key file (optional)
    tls_key="<absolute path .e.g: /etc/chirpstack-gateway-bridge/ievd-v1-12.key>"
